# Generated by Django 5.1.1 on 2024-10-04 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_and_delivery_management', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='cart',
        ),
        migrations.AddField(
            model_name='buyer',
            name='shipping_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='shipping_and_delivery_management.shippingaddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='store_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
