# Generated by Django 5.1.1 on 2024-10-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_shipping_address_orderitem'),
        ('user_management', '0003_buyer_payment_methods_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user_management.buyer'),
            preserve_default=False,
        ),
    ]
